name: release-please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: oven-sh/setup-bun@v2
        if: ${{ steps.release.outputs.release_created }}

      - run: bun install
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to JSR
        run: bunx jsr publish
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to npm
        run: |
          bun run build --if-present
          bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}